name = "ai-chat-api"
main = "worker.js"
compatibility_date = "2024-01-01"

# 生产环境配置
[env.production]
vars = { ENVIRONMENT = "production" }

# 修复路由配置 - 只处理API相关的路径
[[env.production.routes]]
pattern = "bestvip.life/api/*"

[[env.production.routes]]
pattern = "bestvip.life/graphql"

[[env.production.routes]]
pattern = "bestvip.life/health"

[[env.production.routes]]
pattern = "bestvip.life/debug"

# 开发环境
[env.development]
vars = { ENVIRONMENT = "development" }