name = "ai-chat-api"
main = "worker.js"
compatibility_date = "2024-01-01"

# 生产环境配置
[env.production]
vars = { ENVIRONMENT = "production" }

# GraphQL + REST 路由配置 - 使用新域名 sunnyday.pw
[[env.production.routes]]
pattern = "sunnyday.pw/graphql"

[[env.production.routes]]
pattern = "sunnyday.pw/api/*"

[[env.production.routes]]
pattern = "sunnyday.pw/health"

# 开发环境
[env.development]
vars = { ENVIRONMENT = "development" }