name = "ai-chat-api"
main = "worker.js"
compatibility_date = "2024-01-01"

# 生产环境配置
[env.production]
vars = { ENVIRONMENT = "production" }

# 路由配置 - 指向你的域名
[[env.production.routes]]
pattern = "bestvip.life/api/*"

[[env.production.routes]]
pattern = "bestvip.life/graphql"

# 开发环境
[env.development]
vars = { ENVIRONMENT = "development" }